PakistanX/edx-platform

- cms/envs/production.py
- cms/envs/test.py
- lms/djangoapps/branding/views.py
- lms/envs/production.py
- lms/envs/test.py
- lms/urls.py
- openedx/core/djangoapps/user_authn/views/password_reset.py
- openedx/features/pakx_features/__init__.py
- openedx/features/pakx_features/admin.py
- openedx/features/pakx_features/apps.py
- openedx/features/pakx_features/models.py
- openedx/features/pakx_features/tests.py
- openedx/features/pakx_features/views.py
> Change Dashboard landing to courses page

- lms/djangoapps/courseware/views/index.py
- lms/envs/common.py
- lms/envs/devstack.py
- openedx/features/pakx_features/views.py
> EDE-1186 Dashboard cards redirection to About & course home page

- openedx/features/pakx_features/utils.py
- openedx/features/pakx_features/views.py
> EDE-1194 Display Course progress on Dashboard course cards

- lms/djangoapps/courseware/views/index.py
- openedx/features/pakx_features/utils.py
- openedx/features/pakx_features/views.py
> EDE-1217 Mark sections content as completed with user progress

- openedx/features/pakx_features/utils.py
> EDE-1193 Enable google login

- lms/djangoapps/courseware/views/index.py
>  EDE-1195 Display Course effort time on Dashboard course cards

- common/lib/xmodule/xmodule/templates/problem/circuitschematic.yaml
- common/lib/xmodule/xmodule/templates/problem/problem_with_hint.yaml
- common/lib/xmodule/xmodule/templates/problem/problem_with_hint_in_latex.yaml
> EDE-1246 Upgrade xblocks with sample code to python3 code

- common/djangoapps/xblock_django/user_service.py
- common/lib/xmodule/xmodule/html_module.py
- lms/static/js/student_account/views/LoginView.js
> EDE-1243 Show activity inside courses and disable social buttons

- cms/static/sass/elements/_navigation.scss
- common/lib/xmodule/xmodule/css/sequence/display.scss
> EDE- 1240 Some issues found while testing PakistanX on dev server

- common/lib/xmodule/xmodule/js/src/sequence/display.js
> EDE-1241 Unit titles should only appear for active unit only

- lms/envs/common.py
- lms/static/js/student_account/views/FormView.js
- lms/static/js/student_account/views/LoginView.js
- openedx/core/djangoapps/user_authn/views/login_form.py
> EDE-1279 Activity button should be dismissed on close button click

- openedx/core/djangoapps/user_authn/views/login_form.py
> EDE-1242 Add Urdu Nastaliq font

- lms/djangoapps/courseware/views/index.py
- openedx/features/pakx_features/utils.py
> EDE-1244 Add RTL language compatibility

- common/lib/xmodule/xmodule/js/src/sequence/display.js
> EDE-1294 Studio next and previous issue fix

- openedx/features/pakx_features/utils.py
- openedx/features/pakx_features/views.py
> EDE-1283 Course about page, styling update

- common/djangoapps/xblock_django/user_service.py
- common/lib/xmodule/xmodule/html_module.py
> EDE-1338 Pass user first name to HTML xblock

- openedx/features/pakx/lms/overrides/utils.py
> EDE-1395 Update Line height for Urdu font

- common/lib/xmodule/xmodule/js/src/sequence/display.js
Note: This is a partial PR for EDE-1394
> EDE-1394 Fixing courseware navbar scrolling issue

- lms/static/js/student_account/views/LoginView.js
[EDE-1376](https://edlyio.atlassian.net/browse/EDE-1376)
[Theme PR](https://github.com/PakistanX/pakx-theme/pull/42)
> EDE-1376 [PakX] Customize success message on password reset form

- lms/static/js/student_account/views/LoginView.js
> EDE-1376 Show modal to user on Social button click

- openedx/features/course_experience/utils.py
- openedx/features/pakx/lms/overrides/utils.py
- pavelib/prereqs.py
- requirements/pakx/base.txt
**[EDE-1415](https://edlyio.atlassian.net/browse/EDE-1415)** Fixing course progress issue in problem builder
- Create requirements file specific to PakistanX
- Installing xblock `xblock-problem-builder`
- Two core changes will be logged once PR is approved
> EDE-1415 Fixing course progress issue in problem builder

- lms/static/js/student_account/views/account_settings_fields.js
- lms/static/js/views/fields.js
Email sent, the feedback message changed
> PKX-96 Email send, toast message updated

- lms/djangoapps/branding/views.py
- lms/urls.py
- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/urls.py
[PKX-112](https://edlyio.atlassian.net/browse/PKX-112)
[pakx-theme PR](https://github.com/PakistanX/pakx-theme/pull/60)
> PKX-112 Make breadcrumbs on course about page clickable

- openedx/features/pakx/lms/overrides/admin.py
Register BlockCompletion model in Django admin
> EDE-1415 Register BlockCompletion model in Django admin

- cms/envs/test.py
- lms/envs/test.py
- openedx/features/pakx/cms/custom_settings/tests/factories.py
- openedx/features/pakx/cms/custom_settings/tests/test_views.py
- openedx/features/pakx/cms/custom_settings/views.py
[EDE-1372](https://edlyio.atlassian.net/browse/EDE-1372) Unit test for custom settings
Run following command in LMS shell to run unit test
`python -m pytest --ds=cms.envs.test openedx/features/pakx/cms/custom_settings/tests/test_views.py`
> EDE-1372 Unit test for custom settings

- openedx/features/course_experience/utils.py
- openedx/features/pakx/lms/overrides/views.py
Moved user profile page in theme for customization to avoid core change
> PKX-118 Moved user profile page in theme for customization to avoid core change

- openedx/features/pakx/cms/custom_settings/apps.py
- openedx/features/pakx/cms/custom_settings/signals/handlers.py
**[PKX-102](https://edlyio.atlassian.net/browse/PKX-102)** Enable Certificates and add Honor course mode when a new course is created in the studio
> PKX-102 Enable Certificates and add honor course mode

- lms/static/lms/js/build.js
> PKX-133 Learner profile theme factory file added in build js

- openedx/features/course_experience/utils.py
> Added edly kwl XBlock in list for progress calculation

- common/lib/xmodule/xmodule/js/src/sequence/display.js
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
> Updated Drag&Drop XBlock in requirements

- openedx/features/pakx/lms/overrides/signals/handlers.py
- openedx/features/pakx/lms/overrides/tasks.py
> PKX-183 User enrollment issue resolved

- openedx/features/pakx/lms/overrides/signals/handlers.py
- openedx/features/pakx/lms/overrides/tasks.py
> PKX-183 Email Send error fixed

- openedx/features/course_experience/utils.py
- requirements/edx/base.in
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
> PKX-180 Added Image Explorer XBlock, updated py2neo

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> PKX-180 Changed requirements to point to PakistanX image explorer

- openedx/features/pakx/lms/overrides/models.py
- openedx/features/pakx/lms/overrides/signals/handlers.py
- openedx/features/pakx/lms/overrides/tasks.py
[PKX-130](https://edlyio.atlassian.net/browse/PKX-130) Course progress, completion email issue fix
> PKX-130 Course progress, completion email issue fix

- cms/envs/common.py
- openedx/features/course_experience/utils.py
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> PKX-201 XBlock added in requirements & progress list

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> PKX-201 added mentoring xblock in requirements & updated xblock-utils version

- openedx/features/pakx/lms/overrides/tasks.py
> PKX-202 Fixed course progress check issue

- requirements/edx/base.txt
> PKX-202 Bridgekeeper added in base.txt

- lms/static/js/main.js
> PKX-188 Changed main.js form core to verify fix

- openedx/features/pakx/lms/pakx_admin_app/admin.py
- openedx/features/pakx/lms/pakx_admin_app/apps.py
- openedx/features/pakx/lms/pakx_admin_app/models.py
- openedx/features/pakx/lms/pakx_admin_app/tests.py
> PKX-234 pakx admin panel boilerplate django app 

- .github/workflows/python-pylint.yml
- openedx/features/pakx/lms/overrides/tests.py
- pylintrc_tweaks
> Python pylint configured

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
> PKX-261 Updated Drag&Drop version

- cms/envs/devstack.py
- cms/urls.py
- lms/envs/devstack.py
- lms/urls.py
- requirements/edx/development.txt
> PKX-328 added django silk

- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-335 Added analytics APIs, quick stats & learners list 

- openedx/features/pakx/lms/overrides/models.py
- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
- Refactored admin panel APIs
- Added serializer for retrieve user object
- Removed unwanted data from list API
> PKX-341 Refactored admin panel APIs, added serializer for retrieve user object

- openedx/features/pakx/lms/pakx_admin_app/permissions.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
Added user org permission, excluded current user from listing
> Added user org permission, excluded current user from listing

- openedx/features/pakx/lms/pakx_admin_app/utils.py
[PKX-369](https://edlyio.atlassian.net/browse/PKX-369) Update users for listing and analytics
> Updated users for listing and analytics

- openedx/features/pakx/lms/overrides/management/commands/copy_course_enrollments.py
- openedx/features/pakx/lms/overrides/management/commands/send_course_progress_emails.py
- openedx/features/pakx/lms/overrides/signals/handlers.py
- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-376 added courses list api with stats

- openedx/features/pakx/lms/pakx_admin_app/constants.py
- openedx/features/pakx/lms/pakx_admin_app/pagination.py
- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> Fixed registration API fixes

- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> Added all languages, added profile image url, fixed bugs

- openedx/features/pakx/lms/pakx_admin_app/constants.py
- openedx/features/pakx/lms/pakx_admin_app/permissions.py
- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> Fixed and refactored admin panel APIs

- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/constants.py
- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-398 Course enrolment API fixes

- common/lib/xmodule/xmodule/js/src/sequence/display.js
- lms/djangoapps/courseware/views/index.py
> PKX-418 Show Unit names in Accodion

- openedx/core/djangoapps/ace_common/template_context.py
- openedx/core/djangoapps/user_authn/views/password_reset.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
> PKX-433 Added date in base template

- cms/envs/production.py
- lms/envs/production.py
- requirements/edx/base.in
- requirements/edx/base.txt
> PKX-428 Added sentry

- openedx/core/djangoapps/user_authn/views/login.py
> PKX-423 Added no registration link check at login API

- common/lib/xmodule/xmodule/js/src/sequence/display.js
> PKX-421 Active XBlock class added

- openedx/core/djangoapps/user_authn/views/login.py
- openedx/core/djangoapps/user_authn/views/password_reset.py
- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-449 Refactored registration email flow, added account activation link

- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-452 Excluded staff, superuser from WPE course stats

- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
> PKX-458 Updated email context fields name to sync open edx template

- lms/djangoapps/branding/views.py
- lms/urls.py
- openedx/core/djangoapps/user_authn/views/login_form.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-459 Enabled branding page, added business page

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-460 Switched to function based view for MACO templates

- lms/djangoapps/instructor/enrollment.py
- openedx/core/djangoapps/user_authn/views/password_reset.py
- openedx/features/pakx/lms/pakx_admin_app/serializers.py
> PKX-449 Removed last login check from disable reset password email

- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-461 Excluded courses where enrollment status is active

- common/lib/xmodule/xmodule/js/src/sequence/display.js
- lms/djangoapps/courseware/views/index.py
> PKX-414 XBlock selection issue resolved

- openedx/features/pakx/lms/overrides/tasks.py
> PKX-461 Updaed unenrollment task, del entry of CourseProgressStats instead of CourseEnrollment

- common/djangoapps/student/management/commands/recover_account.py
- lms/djangoapps/instructor/enrollment.py
- lms/djangoapps/instructor/views/api.py
- openedx/core/djangoapps/user_authn/views/password_reset.py
> PKX-433 Added user name in reset password email

- .github/pull_request_template.md
- .github/workflows/python-pylint.yml
- lms/djangoapps/courseware/views/index.py
- openedx/features/pakx/lms/overrides/utils.py
> PKX-471 Course language linked with courseware page direction

- common/djangoapps/student/helpers.py
- openedx/core/djangoapps/user_api/accounts/__init__.py
- openedx/core/djangoapps/user_api/accounts/api.py
- openedx/core/djangoapps/user_authn/views/register.py
- openedx/core/djangoapps/user_authn/views/registration_form.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
> PKX-463 Updated public registration name validation and activation email

- common/lib/xmodule/xmodule/js/src/sequence/display.js
> PKX-481 Completion marker added in accordion items

- .github/pull_request_template.md
- .github/workflows/python-pylint.yml
- common/djangoapps/student/helpers.py
- lms/djangoapps/branding/views.py
- lms/djangoapps/courseware/views/index.py
- lms/urls.py
- openedx/core/djangoapps/user_api/accounts/__init__.py
- openedx/core/djangoapps/user_api/accounts/api.py
- openedx/core/djangoapps/user_authn/views/login_form.py
- openedx/core/djangoapps/user_authn/views/register.py
- openedx/core/djangoapps/user_authn/views/registration_form.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
> Mooc develop

- openedx/core/djangoapps/user_authn/views/register.py
> Fixed circular import

- lms/static/js/student_account/views/FormView.js
- openedx/core/djangoapps/user_authn/views/register.py
- openedx/core/djangoapps/user_authn/views/registration_form.py
> PKX-463 Fixed registration validation issues

- common/djangoapps/student/forms.py
- common/djangoapps/student/management/commands/recover_account.py
- common/djangoapps/student/views/management.py
- lms/djangoapps/instructor/views/api.py
- openedx/core/djangoapps/ace_common/template_context.py
- openedx/core/djangoapps/user_api/accounts/views.py
- openedx/core/djangoapps/user_authn/views/password_reset.py
- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
> PKX-473 Added organization in email base context

- cms/djangoapps/contentstore/views/course.py
- cms/envs/common.py
- lms/djangoapps/branding/__init__.py
- lms/envs/common.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-468 Link courses with org and update APIs

- openedx/core/djangoapps/user_authn/views/register.py
> pkx-463 disabled auth after public registration to activate account

- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-470 Pakx whitelisted for Arbisoft, superuser permissions

- lms/djangoapps/instructor/views/api.py
- openedx/features/pakx/lms/pakx_admin_app/tasks.py
> PKX-506 Instructor Email enrollment redesigned

- lms/djangoapps/instructor/enrollment.py
> PKX-506 Date added

- lms/djangoapps/instructor/views/api.py
> PKX-506 Course card & org added

- lms/static/js/student_account/views/LoginView.js
- lms/static/js/student_account/views/RegisterView.js
- lms/templates/student_account/form_field.underscore
> PKX-489 Add toggle password button on password field

- lms/djangoapps/branding/views.py
- lms/djangoapps/courseware/views/index.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-468 Featured course via Site configurations

- lms/djangoapps/branding/api.py
- lms/urls.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/urls.py
> PKX-509 Course about page linked with data

- common/lib/xmodule/xmodule/js/src/sequence/display.js
> PKX-481 QA observations fixed

- lms/static/js/student_account/views/FormView.js
- lms/templates/student_account/form_field.underscore
> PKX-463 Hide hooks errors on Register page

- cms/djangoapps/pipeline_js/js/xmodule.js
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-467 Rating flow started

- cms/envs/common.py
- lms/envs/common.py
> PKX-521 Updated minimum password chars limit

- lms/static/js/student_account/views/AccessView.js
- openedx/core/djangoapps/user_authn/views/register.py
> PKX-463 Added registration success message

- openedx/features/pakx/lms/overrides/forms.py
> PKX-524 Updated contact us page design

- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-519 PKX-520 Added course org logos in about page

- openedx/features/course_experience/utils.py
> PKX-534 PakistanX Grid Dropdown XBlocka added in progress calculation list

- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-509 prerequisite hidden in course about, updated course enrol-able logic 

- openedx/features/pakx/lms/pakx_admin_app/constants.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-468 Fixed user course org conditions

- openedx/features/course_experience/utils.py
- openedx/features/pakx/lms/overrides/utils.py
> PKX-522 Course rating calculation backend implemented

- lms/envs/common.py
- lms/static/js/student_account/views/LoginView.js
> PKX-525 Enable social Login

- openedx/features/pakx/lms/overrides/forms.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-568 Updated placeholders as per requirement

- openedx/features/pakx/lms/pakx_admin_app/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-484 added bulk enrollment

- openedx/features/pakx/lms/pakx_admin_app/serializers.py
> PKX-515 Applied limit of 30 on username of admin panel

- openedx/features/pakx/cms/custom_settings/views.py
> PKX-587 Logo URL forwared slash add fix

- openedx/features/pakx/lms/pakx_admin_app/serializers.py
> PKX-515 Fixed 500 error on user creation

- lms/static/js/student_account/views/AccessView.js
> PKX-581 Fixed redirection to course about page after registration.

- openedx/features/pakx/lms/pakx_admin_app/tasks.py
> PKX-485 Fixed error messages schema

- lms/envs/production.py
- openedx/features/pakx/cms/custom_settings/admin.py
- openedx/features/pakx/cms/custom_settings/models.py
- openedx/features/pakx/common/utils.py
- openedx/features/pakx/lms/overrides/management/commands/create_default_partner_space.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-589 Partner space loading via Query params

- openedx/features/pakx/cms/custom_settings/models.py
- openedx/features/pakx/common/utils.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-629 Space dedicated URL added

- lms/static/js/student_account/views/AccessView.js
- lms/static/js/student_account/views/LoginView.js
- lms/static/js/student_account/views/RegisterView.js
- openedx/core/djangoapps/user_authn/views/login_form.py
- openedx/features/pakx/common/utils.py
> PKX-590 Dynamic Footer links supported

- common/lib/xmodule/xmodule/html_module.py
- lms/djangoapps/courseware/views/index.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-643 Enable public access for course content

- openedx/features/pakx/lms/pakx_admin_app/tasks.py
> PKX 485 sentry issue fix

- cms/envs/common.py
- lms/djangoapps/courseware/views/index.py
- lms/djangoapps/experiments/utils.py
- openedx/features/course_experience/views/course_outline.py
- openedx/features/pakx/cms/custom_settings/migrations/0001_initial.py
> PKX-605 Accordion & course page imports fixed

- openedx/features/pakx/lms/pakx_admin_app/tasks.py
> PKX-485 Fixed bulk registration key error

- lms/djangoapps/courseware/views/index.py
- lms/envs/devstack.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-616 Added workplace essentials showcase page

- lms/static/js/student_account/views/LoginView.js
- openedx/features/pakx/lms/overrides/forms.py
- openedx/features/pakx/lms/overrides/views.py
PKX-653- rebrand PakistanX to ilmX, platform-related changes
> rebrand pakX to ilmX

- openedx/features/pakx/lms/overrides/urls.py
> PKX-666 Replace business page with w.e demo courses

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-664 Added terms and privacy page

- openedx/features/pakx/lms/pakx_admin_app/serializers.py
> PKX-631 Fixed wrong date showing on course enrolment

- openedx/features/pakx/cms/custom_settings/migrations/0006_merge_20211129_1131.py
> Migration operation method, params added

- cms/envs/common.py
- common/djangoapps/util/milestones_helpers.py
- lms/djangoapps/course_api/blocks/transformers/milestones.py
- lms/envs/common.py
- openedx/features/pakx/cms/custom_settings/views.py
- openedx/features/pakx/lms/overrides/management/commands/check_and_unlock_learner_milestones.py
- openedx/features/pakx/lms/overrides/message_types.py
> PKX-673 Added email support

- lms/djangoapps/branding/api.py
- openedx/features/pakx/common/utils.py
> PKX-681 Updated space logo and fav icons

- openedx/core/djangoapps/coursegraph/management/commands/dump_to_neo4j.py
- openedx/core/djangoapps/coursegraph/management/commands/tests/test_dump_to_neo4j.py
- openedx/core/djangoapps/coursegraph/management/commands/tests/utils.py
- openedx/core/djangoapps/coursegraph/tasks.py
- requirements/constraints.txt
- requirements/edx/base.in
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
> PKX-697 Py2neo version updated

- cms/envs/production.py
- lms/djangoapps/course_api/blocks/serializers.py
> minor bug fixes

- cms/djangoapps/contentstore/views/item.py
- common/lib/xmodule/xmodule/seq_module.py
- openedx/core/lib/gating/api.py
- openedx/features/pakx/cms/custom_settings/views.py
- openedx/features/pakx/lms/overrides/management/commands/check_and_unlock_learner_milestones.py
- openedx/features/pakx/lms/overrides/utils.py
> PKX-623 Scheduled release of subsection

- openedx/features/pakx/lms/overrides/management/commands/check_and_unlock_learner_milestones.py
> PKX-673 Fixed image url template

- cms/djangoapps/contentstore/views/item.py
- common/lib/xmodule/xmodule/seq_module.py
- openedx/core/lib/gating/api.py
- openedx/features/pakx/cms/custom_settings/views.py
- openedx/features/pakx/lms/overrides/management/commands/check_and_unlock_learner_milestones.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/pakx_admin_app/permissions.py
- openedx/features/pakx/lms/pakx_admin_app/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
lilac upgrade rebase version 3
> rebase lilac upgrade version 3

- openedx/features/pakx/lms/pakx_admin_app/permissions.py
> PKX-682 Fixed same organization permission org check

- cms/envs/common.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-699 Course about page dir attribute added

- openedx/features/pakx/lms/overrides/migrations/0003_auto_20210628_1006.py
> Overrides app, migration dependancy updated

- common/djangoapps/student/migrations/0043_userprofile_organization.py
> UPDATED migration dependancy

- cms/djangoapps/contentstore/views/item.py
- cms/envs/common.py
- openedx/core/lib/gating/api.py
- openedx/features/pakx/cms/custom_settings/views.py
- openedx/features/pakx/lms/overrides/management/commands/check_and_unlock_learner_milestones.py
- openedx/features/pakx/lms/overrides/views.py
> Juniper changes rebased

- common/djangoapps/student/migrations/0043_userprofile_organization.py
- openedx/features/pakx/lms/overrides/migrations/0003_auto_20210628_1006.py
> Migration Dependancy typo fixed

- .github/workflows/python-pylint.yml
- cms/djangoapps/contentstore/views/item.py
> STUDIO missing import added

- openedx/features/pakx/lms/overrides/tabs.py
- setup.py
> Version Updated for Overview Tab

- openedx/core/djangoapps/user_authn/views/login_form.py
- openedx/core/djangoapps/user_authn/views/registration_form.py
- openedx/features/pakx/lms/overrides/forms.py
- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-733 Placeholder for forms updated

- lms/djangoapps/branding/api.py
- openedx/core/djangoapps/user_authn/views/login_form.py
- openedx/core/djangoapps/user_authn/views/registration_form.py
- openedx/features/pakx/lms/overrides/forms.py
- openedx/features/pakx/lms/overrides/views.py
> Synched with Lilac develop

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> PKX-734 Updated image explorer version

- openedx/core/djangoapps/user_authn/views/registration_form.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-736 Active Campaign replaced featured course flow

- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-736 Active Campaign QA Observation fixed

- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-705 Filtered Video XBlock to Video & carousel as Problem

- openedx/features/pakx/lms/overrides/admin.py
> PKX-767 Course progress stats filter for org & course title added

- openedx/features/pakx/lms/overrides/utils.py
> PKX-706 Progress percentage issue fixe

- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/urls.py
> PKX-706 Fixed observations on progress page

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> xblock-mentoring updated in requirements

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> PKX-797 Updated mentoring & ooyala XBlocks to PakistanX cloned version

- openedx/features/pakx/lms/overrides/utils.py
> PKX-798 Course about page crash fixed

- lms/envs/common.py
> PKX-795 Enabled ecommerce

- openedx/core/djangoapps/user_authn/views/login_form.py
- openedx/core/djangoapps/user_authn/views/registration_form.py
- openedx/features/pakx/lms/overrides/forms.py
> PKX-803 Updated Placeholders for email & Join Now text

- common/lib/xmodule/xmodule/seq_module.py
- openedx/features/pakx/lms/overrides/management/commands/check_and_unlock_learner_milestones.py
- openedx/features/pakx/lms/overrides/post_assessment.py
- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/overrides/utils.py
> Moved post assessment functionality to celery task

- openedx/features/pakx/common/utils.py
- openedx/features/pakx/lms/overrides/utils.py
> PKX-799 Course org issue fixed

- lms/djangoapps/branding/api.py
> PKX-857 Changed homepage redirection to dashboard instead of root

- lms/djangoapps/courseware/views/index.py
- openedx/features/pakx/common/utils.py
> PKX-815 Added icon for video experience

- openedx/features/pakx/lms/overrides/views.py
> PKX-872 Fixed ripples caused by enable course discovery flag

- lms/djangoapps/branding/api.py
> PKX-873 Revert logo redirection back to root from dashboard

- lms/djangoapps/discussion/config/waffle.py
- openedx/features/course_experience/__init__.py
> PKX-883 Disabled bootstrap flags

- common/static/common/js/discussion/discussion.js
- common/static/common/js/discussion/views/discussion_thread_list_view.js
- common/static/common/templates/discussion/templates.underscore
> Implemented Filters

- lms/djangoapps/discussion/static/discussion/js/views/discussion_board_view.js
- lms/djangoapps/discussion/static/discussion/templates/discussion-home.underscore
> PKX-889 Added hide/show for discussion instructions

- openedx/features/pakx/lms/overrides/utils.py
> PKX-883 Added accordion in sidebar

- common/static/common/templates/discussion/templates.underscore
> comment section style

- common/static/common/js/discussion/views/discussion_thread_view.js
- common/static/common/templates/discussion/templates.underscore
> comment area style

- common/static/common/js/discussion/views/new_post_view.js
- common/static/common/templates/discussion/templates.underscore
> Add post changes

- common/static/common/templates/discussion/templates.underscore
> style inline discussion

- common/static/common/templates/discussion/templates.underscore
> PKX-882 ICONS added for post close

- lms/djangoapps/discussion/static/discussion/templates/discussion-home.underscore
> PKX-941 qa fixs

- common/lib/xmodule/xmodule/seq_module.py
- openedx/features/pakx/lms/overrides/utils.py
> PKX-938 Saved progress on calculation on next click from LMS

- common/static/common/templates/discussion/templates.underscore
>  940 qa fix

- common/lib/xmodule/xmodule/js/src/sequence/display.js
- common/lib/xmodule/xmodule/seq_module.py
- openedx/features/pakx/lms/overrides/utils.py
> PKX-938 Saved progress in the same format as in progress bar

- common/lib/xmodule/xmodule/js/src/sequence/display.js
> PKX-954 Course progress fetching disabled for studio view

- common/static/common/js/discussion/views/discussion_content_view.js
- common/static/common/js/discussion/views/discussion_thread_list_view.js
- common/static/common/js/discussion/views/discussion_thread_view.js
- common/static/common/js/discussion/views/response_comment_view.js
- common/static/common/js/discussion/views/thread_response_view.js
- lms/djangoapps/discussion/views.py
> PKX-940 Fixed issue 71

- openedx/features/pakx/lms/overrides/utils.py
> PKX-916 XBlock added in Core XBlock types

- common/static/common/js/discussion/discussion.js
- common/static/common/js/discussion/utils.js
- common/static/common/js/discussion/views/discussion_thread_list_view.js
- common/static/common/templates/discussion/templates.underscore
- lms/djangoapps/discussion/static/discussion/js/discussion_router.js
- lms/djangoapps/discussion/views.py
> PKX-955 Fixed according to QA observations

- common/static/common/js/discussion/views/discussion_thread_list_view.js
- lms/djangoapps/discussion/views.py
> PKX-940 Fixed filter and search issue

- openedx/features/pakx/lms/overrides/admin.py
> PKX-949 Download as CSV action added for Course Progress Stats

- openedx/features/course_experience/utils.py
- openedx/features/pakx/lms/overrides/utils.py
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> PKX-971 Excluded MicroLearning and ilmX Completion from Progress tracking

- openedx/features/pakx/lms/overrides/utils.py
> Moved Edly & PakX Assessment to other type

- openedx/features/pakx/lms/overrides/forms.py
> PKX-1006 Update helper text for message in Contact Form

- cms/envs/common.py
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> PKX-966 MincroLearning added in requirements and switched completion to branch based

- openedx/features/pakx/lms/overrides/views.py
> PKX-1016 Fixed crash on about page

- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-1027 Added filters for learners

- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-1028 Added Course filters, search and ordered by course name

- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-1029 Enabled CSV generation and download for learner stats

- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-1030 Enabled CSV generation and download for course stats

- common/static/common/js/discussion/utils.js
- common/static/common/js/discussion/views/discussion_thread_list_view.js
- common/static/common/js/discussion/views/discussion_topic_menu_view.js
- common/static/common/js/discussion/views/new_post_view.js
- common/static/common/templates/discussion/templates.underscore
- lms/djangoapps/discussion/static/discussion/js/views/discussion_board_view.js
> PKX-895 Discussion responsive view changes

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-1044 Added static landing page

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-1044 Fixed empty url

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-1044 Removed testing URL

- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-1026 Admin Panel Course and Learners Filters and CSV Report Generation (#327)

- openedx/features/pakx/lms/pakx_admin_app/views.py
> PKX-1032 Fixed according to QA observations

- openedx/features/pakx/lms/overrides/signals/handlers.py
> PKX-1099 Added automatic verification of learners if they are enrolling in a verified course

- common/lib/xmodule/xmodule/js/src/sequence/display.js
> PKX-1080 Handled null error

- common/djangoapps/student/views/management.py
- lms/static/js/student_account/models/RegisterModel.js
- openedx/core/djangoapps/user_authn/views/register.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
> PKX-1146 Send next URL in account activation mail

- openedx/features/pakx/cms/custom_settings/models.py
- openedx/features/pakx/cms/custom_settings/views.py
- openedx/features/pakx/lms/overrides/utils.py
- openedx/features/pakx/lms/overrides/views.py
> Add FAQ field in Custom Settings

- openedx/features/pakx/lms/overrides/views.py
> Update time format

- common/djangoapps/student/views/management.py
> PKX-1046 Tried fix for redirection

- common/djangoapps/student/helpers.py
> PKX-1079 Fixed redirection after login for course about pages with pakx org

- openedx/core/djangoapps/user_authn/cookies.py
> Add user_role in Cookies Header

- .gitignore
- cms/envs/common.py
- openedx/features/course_experience/utils.py
- openedx/features/pakx/lms/overrides/utils.py
> Add configuration for Journal Xblock

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> PKX-1199 Changed approach of redirection

- openedx/features/pakx/lms/overrides/utils.py
> Journal Xblock: Moved from problem to others in progress page

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
[PKX-1199]: https://edlyio.atlassian.net/browse/PKX-1199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1199 Changed redirection approach

- openedx/features/pakx/lms/overrides/views.py
[PKX-1243]: https://edlyio.atlassian.net/browse/PKX-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1243 Added Persian course to the new about page list

- openedx/core/djangoapps/user_api/accounts/api.py
> Integerate emailable to verify emails

- common/djangoapps/student/views/management.py
- openedx/core/djangoapps/user_authn/views/register.py
[PKX-1200]: https://edlyio.atlassian.net/browse/PKX-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1200 Redirected to cart after activating account

- openedx/features/pakx/lms/discover/views.py
[PKX-1207]: https://edlyio.atlassian.net/browse/PKX-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1207 Fixed crash due to import of function

- common/static/common/templates/discussion/templates.underscore
> Fixed discussion mobile button showing on desktop view

- openedx/core/djangoapps/user_authn/views/logout.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
[PKX-1242]: https://edlyio.atlassian.net/browse/PKX-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1242 Added redirects to wordpress site

- openedx/features/pakx/lms/overrides/views.py
> Added 21st Century course to new about page template list

- openedx/features/pakx/lms/overrides/tasks.py
> Changed mode of users enrolled from admin panel from honor to verified

- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
[PKX-1283]: https://edlyio.atlassian.net/browse/PKX-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1283 Added enrollment change option from admin panel

- lms/envs/common.py
- lms/static/js/student_account/views/RegisterView.js
- openedx/core/djangoapps/user_api/accounts/api.py
- openedx/core/djangoapps/user_authn/views/register.py
[PKX-1198]: https://edlyio.atlassian.net/browse/PKX-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1198 Replaced email verification with IsItRealEmail API

- openedx/features/pakx/lms/discover/urls.py
- openedx/features/pakx/lms/discover/views.py
[PKX-1286]: https://edlyio.atlassian.net/browse/PKX-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1286 Functional changes for CAP high touch

- openedx/features/pakx/lms/discover/urls.py
- openedx/features/pakx/lms/discover/views.py
[PKX-1286]: https://edlyio.atlassian.net/browse/PKX-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1286 Fixed ID issue in course about wp

- openedx/features/pakx/lms/discover/urls.py
- openedx/features/pakx/lms/discover/views.py
[PKX-1318]: https://edlyio.atlassian.net/browse/PKX-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1318 Fixed logo for business logos in wordpress

- openedx/features/pakx/lms/discover/urls.py
- openedx/features/pakx/lms/discover/views.py
[PKX-1318]: https://edlyio.atlassian.net/browse/PKX-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1318 Changed org name approach

- .github/workflows/python-pylint.yml
- openedx/features/pakx/lms/discover/views.py
[PKX-1286]: https://edlyio.atlassian.net/browse/PKX-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1286 Fixed empty same course ID in recommended courses

- openedx/features/pakx/lms/discover/views.py
[PKX-1209]: https://edlyio.atlassian.net/browse/PKX-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1209 Added course ID for upcoming courses

- lms/djangoapps/courseware/views/index.py
[PKX-1278]: https://edlyio.atlassian.net/browse/PKX-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1278 Add user fullname in Tooltip popup

- .gitignore
- lms/envs/common.py
> remove unused PDF paths

- openedx/features/pakx/lms/discover/views.py
[PKX-1359]: https://edlyio.atlassian.net/browse/PKX-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1359 Added price for verified and audit courses

- openedx/features/pakx/lms/discover/views.py
[PKX-1359]: https://edlyio.atlassian.net/browse/PKX-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1359 Changed price from PKR to Rs

- openedx/features/pakx/lms/overrides/views.py
> Handled milestone condition on about page for anonymous users

- common/static/common/js/discussion/views/discussion_thread_edit_view.js
- common/static/common/js/discussion/views/new_post_view.js
> Fixed show more button on edit post

- common/static/common/js/discussion/views/discussion_thread_edit_view.js
- common/static/common/js/discussion/views/new_post_view.js
- common/static/common/templates/discussion/templates.underscore
[PKX-1042]: https://edlyio.atlassian.net/browse/PKX-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1042 Discussion forum mobile view fixes

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
[PKX-1374]: https://edlyio.atlassian.net/browse/PKX-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1374 Added PSW redirect view on LMS

- openedx/features/pakx/lms/overrides/constants.py
[PKX-1375]: https://edlyio.atlassian.net/browse/PKX-1375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1375 Added courses in 5e Model List

- openedx/features/pakx/lms/pakx_admin_app/serializers.py
- openedx/features/pakx/lms/pakx_admin_app/tasks.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
[PKX-1368]: https://edlyio.atlassian.net/browse/PKX-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1368 Changed registration email CTA

- cms/envs/common.py
- openedx/features/course_experience/utils.py
- openedx/features/pakx/lms/overrides/utils.py
> Integrated Github Xblock

- openedx/core/djangoapps/user_authn/views/register.py
- openedx/features/pakx/lms/overrides/signals/handlers.py
- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/overrides/views.py
[PKX-1419]: https://edlyio.atlassian.net/browse/PKX-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1419 Added active campaign events

- lms/static/js/student_account/models/LoginModel.js
- lms/static/js/student_account/models/RegisterModel.js
- openedx/features/pakx/lms/overrides/tasks.py
[PKX-1420]: https://edlyio.atlassian.net/browse/PKX-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1420 Added GA events on successful login and signup

- openedx/features/pakx/lms/overrides/constants.py
[PKX-1422]: https://edlyio.atlassian.net/browse/PKX-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1422 Added project management course for redirection

- openedx/core/djangoapps/user_authn/views/register.py
- openedx/features/pakx/lms/overrides/signals/handlers.py
- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/overrides/views.py
This reverts commit 7a90bdae8652f629207f5130fa2e2213e75be51f.
> Revert "PKX-1419 Added active campaign events (#406)"

- common/lib/xmodule/xmodule/seq_module.py
- lms/djangoapps/course_blocks/transformers/user_partitions.py
- openedx/core/djangoapps/user_authn/views/login_form.py
- openedx/features/pakx/lms/overrides/constants.py
[PKX-1431]: https://edlyio.atlassian.net/browse/PKX-1431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1431: Update "Join now" to "Signup"

- openedx/features/pakx/lms/overrides/constants.py
> ASK: Enable LUMS certificate for TCF org

- openedx/features/pakx/lms/overrides/constants.py
[PKX-1444]: https://edlyio.atlassian.net/browse/PKX-1444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1444: Update CAP url for AI course

- common/djangoapps/util/cache.py
- openedx/features/pakx/lms/overrides/constants.py
> Ask enable LUMS certificate for Jadid Dastgir

- openedx/features/pakx/lms/overrides/constants.py
> ASK: Enable LUMS certificate for happy place 5E course

- lms/djangoapps/commerce/api/v1/urls.py
- lms/djangoapps/commerce/api/v1/views.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/pakx_admin_app/message_types.py
> COD order email

- openedx/features/pakx/lms/overrides/constants.py
> ASK: Enable LUMs certificate for Risk Associates

- openedx/features/pakx/lms/overrides/constants.py
> ASK: Enable LUMs certificate for Amal Academy

- lms/djangoapps/commerce/api/v1/urls.py
- lms/djangoapps/commerce/api/v1/views.py
- openedx/features/pakx/lms/overrides/constants.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/pakx_admin_app/message_types.py
> Track prod deployment main branch

- openedx/features/pakx/lms/overrides/constants.py
- openedx/features/pakx/lms/overrides/signals/handlers.py
- openedx/features/pakx/lms/overrides/tasks.py
> FIX: progress course email + manual verification bug

- openedx/features/pakx/lms/overrides/constants.py
- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
> Sync main with develop using backmerge 08-July-2024

- openedx/features/pakx/lms/pakx_admin_app/message_types.py
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
> change edx-ora2 repo source to pakx fork

- openedx/core/djangoapps/models/course_details.py
> PKX-1454: Optimize CAP

- openedx/features/pakx/lms/pakx_admin_app/constants.py
- openedx/features/pakx/lms/pakx_admin_app/urls.py
- openedx/features/pakx/lms/pakx_admin_app/views.py
[PKX-1469]: https://edlyio.atlassian.net/browse/PKX-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1469: Added view to reset password via admin panel frontend

- openedx/features/pakx/lms/pakx_admin_app/views.py
[PKX-1469]: https://edlyio.atlassian.net/browse/PKX-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1469: reset password bulk

- lms/djangoapps/instructor_task/tasks_helper/grades.py
[PKX-1470]: https://edlyio.atlassian.net/browse/PKX-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1470: Grade report changes

- openedx/features/pakx/lms/pakx_admin_app/views.py
[PKX-1471]: https://edlyio.atlassian.net/browse/PKX-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKX-1471: Enhance login stats view

- openedx/core/djangoapps/user_authn/urls_common.py
- openedx/core/djangoapps/user_authn/views/register.py
> LUMSx checkout registration form validation API

- openedx/features/pakx/lms/overrides/urls.py
- openedx/features/pakx/lms/overrides/views.py
- openedx/features/pakx/lms/pakx_admin_app/utils.py
> Integrate LUMSx order checkout

- openedx/features/pakx/lms/overrides/views.py
> LUMSx checkout integration improvements

- lms/envs/common.py
- openedx/features/pakx/lms/overrides/constants.py
- openedx/features/pakx/lms/overrides/middleware.py
- openedx/features/pakx/lms/overrides/tasks.py
- openedx/features/pakx/lms/overrides/views.py
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
> Integrate SCORM XBlock
